export const Effects = [
    { id: "bleeding", name: "ADS.EFFECT.StatusBleeding", img: "systems/aeon-draw-steel/icons/effects/bleeding.svg" },
    { id: "dead", name: "ADS.EFFECT.StatusDead", img: "icons/svg/skull.svg" },
    { id: "dazed", name: "ADS.EFFECT.StatusDazed", img: "systems/aeon-draw-steel/icons/effects/dazed.svg" },
    { id: "grabbed", name: "ADS.EFFECT.StatusGrabbed", img: "systems/aeon-draw-steel/icons/effects/grabbed.svg" },
    { id: "frightened", name: "ADS.EFFECT.StatusFrightened", img: "icons/svg/terror.svg" },
    { id: "invisible", name: "ADS.EFFECT.StatusInvisible", img: "icons/svg/invisible.svg" },
    { id: "judged", name: "ADS.EFFECT.StatusJudged", img: "systems/aeon-draw-steel/icons/effects/judged.svg" },
    { id: "marked", name: "ADS.EFFECT.StatusMarked", img: "icons/svg/target.svg" },
    { id: "prone", name: "ADS.EFFECT.StatusProne", img: "icons/svg/falling.svg" },
    { id: "restrained", name: "ADS.EFFECT.StatusRestrained", img: "systems/aeon-draw-steel/icons/effects/restrained.svg" },
    { id: "slowed", name: "ADS.EFFECT.StatusSlowed", img: "systems/aeon-draw-steel/icons/effects/slowed.svg" },
    { id: "surprised", name: "ADS.EFFECT.StatusSurprised", img: "systems/aeon-draw-steel/icons/effects/surprised.svg" },
    { id: "sustaining", name: "ADS.EFFECT.StatusSustaining", img: "systems/aeon-draw-steel/icons/effects/sustaining.svg" },
    { id: "taunted", name: "ADS.EFFECT.StatusTaunted", img: "systems/aeon-draw-steel/icons/effects/taunted.svg" },
    { id: "unconscious", name: "ADS.EFFECT.StatusUnconscious", img: "icons/svg/sleep.svg" },
    { id: "weakened", name: "ADS.EFFECT.StatusWeakened", img: "systems/aeon-draw-steel/icons/effects/weakened.svg" },    
    { id: "winded", name: "ADS.EFFECT.StatusWinded", img: "systems/aeon-draw-steel/icons/effects/winded.svg" },

    // { id: "strengthened", name: "EFFECT.StatusMinotaur", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/minotaur-svgrepo-com.svg" },
    // { id: "sandsOfTime", name: "EFFECT.StatusSands Of Time", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/sands-of-time-svgrepo-com.svg" },
    // { id: "walkingBoot", name: "EFFECT.StatusWalking Boot", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/walking-boot-svgrepo-com.svg" },
    // { id: "barbedSun", name: "EFFECT.StatusBarbed Sun", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/barbed-sun-svgrepo-com.svg" },
    // { id: "crackedShield", name: "EFFECT.StatusCracked Shield", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/cracked-shield-svgrepo-com.svg" },
    // { id: "crossedSwords1", name: "EFFECT.StatusCrossed Swords", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/surrounded-shield-svgrepo-com.svg" },
    // { id: "crossedSwords2", name: "EFFECT.StatusCrossed Swords", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/oily-spiral-svgrepo-com (1).svg" },
    // { id: "crossedSwords3", name: "EFFECT.StatusCrossed Swords", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/eclipse-flare-svgrepo-com (1).svg" },
    // { id: "crossedSwords4", name: "EFFECT.StatusCrossed Swords", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/edged-shield-svgrepo-com.svg" },
    // { id: "judged", name: "EFFECT.StatusJudged", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/sheikah-eye-svgrepo-com.svg" },
    // { id: "tripleClaws", name: "EFFECT.StatusTriple Claws", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/triple-claws-svgrepo-com.svg" },
    // { id: "aura", name: "EFFECT.StatusAura", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/aura-svgrepo-com.svg" },
    // { id: "bowman", name: "EFFECT.StatusBowman", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/bowman-svgrepo-com.svg" },
    // { id: "dazed", name: "EFFECT.StatusDazed", img: "icons/svg/daze.svg" },
    // { id: "weakened", name: "EFFECT.StatusWeakened", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/back-pain-svgrepo-com.svg" },
    // { id: "curvyKnife", name: "EFFECT.StatusCurvy Knife", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/curvy-knife-svgrepo-com.svg" },
    // { id: "fireSilhouette", name: "EFFECT.StatusFire Silhouette", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/fire-silhouette-svgrepo-com.svg" },
    // { id: "fluffyCloud", name: "EFFECT.StatusFluffy Cloud", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/fluffy-cloud-svgrepo-com.svg" },
    // { id: "fluffyFlame", name: "EFFECT.StatusFluffy Flame", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/fluffy-flame-svgrepo-com.svg" },
    // { id: "winded2", name: "EFFECT.StatusWinded", img: "systems/aeon-draw-steel/icons/svg/statuses/exhaustion.svg" },
    // { id: "huntingHorn", name: "EFFECT.StatusHunting Horn", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/hunting-horn-svgrepo-com.svg" },
    // { id: "scales", name: "EFFECT.StatusScales", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/scales-svgrepo-com.svg" },

    // { id: "smallFire", name: "EFFECT.StatusSmall Fire", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/small-fire-svgrepo-com.svg" },

    // { id: "steeltoeBoots", name: "EFFECT.StatusSteeltoe Boots", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/steeltoe-boots-svgrepo-com.svg" },
    // { id: "strong", name: "EFFECT.StatusStrong", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/strong-svgrepo-com.svg" },
    // { id: "sun", name: "EFFECT.StatusSun", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/sun-svgrepo-com.svg" },
    // { id: "swordClash", name: "EFFECT.StatusSword Clash", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/sword-clash-svgrepo-com.svg" },
    // { id: "thrownSpear", name: "EFFECT.StatusThrown Spear", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/thrown-spear-svgrepo-com.svg" },
    // { id: "tiedScroll", name: "EFFECT.StatusTied Scroll", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/tied-scroll-svgrepo-com.svg" },
    // { id: "tornadoDiscs", name: "EFFECT.StatusTornado Discs", img: "systems/aeon-draw-steel/icons/svg/statuses/temp/tornado-discs-svgrepo-com.svg" },
    // { id: "paralysis", name: "EFFECT.StatusParalysis", img: "icons/svg/paralysis.svg" },
    // { id: "silence", name: "EFFECT.StatusSilenced", img: "icons/svg/silenced.svg" },
    // { id: "blind", name: "EFFECT.StatusBlind", img: "icons/svg/blind.svg" },
    // { id: "deaf", name: "EFFECT.StatusDeaf", img: "icons/svg/deaf.svg" },
    // { id: "burning", name: "EFFECT.StatusBurning", img: "icons/svg/fire.svg" },
    // { id: "frozen", name: "EFFECT.StatusFrozen", img: "icons/svg/frozen.svg" },
    // { id: "shock", name: "EFFECT.StatusShocked", img: "icons/svg/lightning.svg" },
    // { id: "corrode", name: "EFFECT.StatusCorrode", img: "icons/svg/acid.svg" },
    // { id: "disease", name: "EFFECT.StatusDisease", img: "icons/svg/biohazard.svg" },
    // { id: "poison", name: "EFFECT.StatusPoison", img: "icons/svg/poison.svg" },
    // { id: "curse", name: "EFFECT.StatusCursed", img: "icons/svg/sun.svg" },
    // { id: "regen", name: "EFFECT.StatusRegen", img: "icons/svg/regen.svg" },
    // { id: "degen", name: "EFFECT.StatusDegen", img: "icons/svg/degen.svg" },
    // { id: "hover", name: "EFFECT.StatusHover", img: "icons/svg/wingfoot.svg" },
    // { id: "burrow", name: "EFFECT.StatusBurrow", img: "icons/svg/mole.svg" },
    // { id: "upgrade", name: "EFFECT.StatusUpgrade", img: "icons/svg/upgrade.svg" },
    // { id: "downgrade", name: "EFFECT.StatusDowngrade", img: "icons/svg/downgrade.svg" },
    // { id: "bless", name: "EFFECT.StatusBlessed", img: "icons/svg/angel.svg" },
    // { id: "fireShield", name: "EFFECT.StatusFireShield", img: "icons/svg/fire-shield.svg" },
    // { id: "coldShield", name: "EFFECT.StatusIceShield", img: "icons/svg/ice-shield.svg" },
    // { id: "magicShield", name: "EFFECT.StatusMagicShield", img: "icons/svg/mage-shield.svg" },
    // { id: "holyShield", name: "EFFECT.StatusHolyShield", img: "icons/svg/holy-shield.svg" }
]
